### ISSUE TITLE
Node.js warning

### ISSUE THREAD

**Issue by kemalcany** [ritz078/rollup-plugin-filesize#30]
Hi there,

Thanks for the repo!

I've been receiving this warning during my builds, is this something anyone else is experiencing?

Thanks

`(node:24726) Warning: N-API is an experimental feature and could change at any time.`

**Comment by jhoffmcd** [comment]
I've been seeing this too, is it coming from this plugin for sure?

**Comment by ritz078** [comment]
I don't think it's coming from this plugin.

**Comment by zenflow** [comment]
@ritz078 It is coming from this plugin, or *a dependency of* this plugin. I am pretty sure of this, because I wasn't getting this warning, and then I installed this package and started using it.

Could we reopen this, since it is a problem this package brings in? This package should ideally not be using any package that relies on an unstable/experimental node API.

**Comment by ritz078** [comment]
I will check that. A PR for fix is welcome. meanwhile re opening the issue.

**Comment by brettz9** [comment]
N-API is stable as of Node 10. Since the Github Actions are only testing 10 and 12, @ritz078 , do you want to make a breaking change and bump `engines` to Node 10. In such a case, this issue could be closed.

Btw, the Actions should probably also test Node 14.

**Comment by ritz078** [comment]
> do you want to make a breaking change and bump engines to Node 10

Yes. It does make sense. Node 10 seems like a valid change since lot of other libraries already do that.

> Actions should probably also test Node 14

Done
